/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as KeyboardGameRouteImport } from './routes/keyboard-game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiKeyboardLeaderboardRouteImport } from './routes/api/keyboard-leaderboard'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyboardGameRoute = KeyboardGameRouteImport.update({
  id: '/keyboard-game',
  path: '/keyboard-game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeyboardLeaderboardRoute = ApiKeyboardLeaderboardRouteImport.update({
  id: '/api/keyboard-leaderboard',
  path: '/api/keyboard-leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/keyboard-game': typeof KeyboardGameRoute
  '/resume': typeof ResumeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/keyboard-leaderboard': typeof ApiKeyboardLeaderboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/keyboard-game': typeof KeyboardGameRoute
  '/resume': typeof ResumeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/keyboard-leaderboard': typeof ApiKeyboardLeaderboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/keyboard-game': typeof KeyboardGameRoute
  '/resume': typeof ResumeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/keyboard-leaderboard': typeof ApiKeyboardLeaderboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/keyboard-game'
    | '/resume'
    | '/api/chat'
    | '/api/keyboard-leaderboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/keyboard-game'
    | '/resume'
    | '/api/chat'
    | '/api/keyboard-leaderboard'
  id:
    | '__root__'
    | '/'
    | '/keyboard-game'
    | '/resume'
    | '/api/chat'
    | '/api/keyboard-leaderboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KeyboardGameRoute: typeof KeyboardGameRoute
  ResumeRoute: typeof ResumeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiKeyboardLeaderboardRoute: typeof ApiKeyboardLeaderboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keyboard-game': {
      id: '/keyboard-game'
      path: '/keyboard-game'
      fullPath: '/keyboard-game'
      preLoaderRoute: typeof KeyboardGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keyboard-leaderboard': {
      id: '/api/keyboard-leaderboard'
      path: '/api/keyboard-leaderboard'
      fullPath: '/api/keyboard-leaderboard'
      preLoaderRoute: typeof ApiKeyboardLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KeyboardGameRoute: KeyboardGameRoute,
  ResumeRoute: ResumeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiKeyboardLeaderboardRoute: ApiKeyboardLeaderboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
